# Generated by Django 5.2.11 on 2026-02-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_result_avg_key_interval_result_keystroke_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingtest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
